check:
  - thoth-build
build:
  base-image: quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.27.0
  build-strategy: Source
  registry: quay.io
  registry-org: thoth-station
  registry-project: pipeline-helpers
  registry-secret: thoth-station-thoth-pusher-secret
