presubmits:
  - name: pre-commit
    decorate: true
    skip_report: false
    always_run: true
    context: op1st/prow/pre-commit
    spec:
      containers:
        - image: quay.io/thoth-station/thoth-precommit-py38:v0.12.9
          command:
            - "pre-commit"
            - "run"
            - "--all-files"
          resources:
            requests:
              memory: "500Mi"
              cpu: "300m"
            limits:
              memory: "1Gi"
              cpu: "300m"

  - name: thoth-mypy-py38
    decorate: true
    skip_report: false
    always_run: true
    context: op1st/prow/mypy
    spec:
      containers:
        - image: quay.io/thoth-station/thoth-pytest-ubi8-py38:v0.12.9
          command:
            - "/usr/local/bin/mypy"
            - "."
            - "--ignore-missing-imports"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
